services:
  mdns-monitor:
    container_name: mdns-monitor
    image: dciancu/mdns-monitor
    init: true
    read_only: true
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: 'UTC'
      WEB_ADDRESS: '0.0.0.0'
      WEB_PORT: 3000
