services:
  mdns-monitor:
    container_name: mdns-monitor
    image: dciancu/mdns-monitor
    init: true
    read_only: true
    restart: unless-stopped
    environment:
      TZ: 'UTC'
      WEB_ADDRESS: '0.0.0.0'
      WEB_PORT: 3000
#    ports:
#      - "5353:5353/udp" # Caution: macOS mDNS is already bound
#      - "3000:3000/tcp" # WEB_PORT above
