version: 2.1
jobs:
  build-arm:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: true
    resource_class: arm.medium
    environment:
      BUILDKIT_PROGRESS: plain
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "src/yarn.lock" }}
      - run:
          name: Build
          command: ./build.sh
      - save_cache:
          key: node_modules-{{ checksum "src/yarn.lock" }}
          paths:
            - src/node_modules
  build-x86:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: true
    resource_class: medium
    environment:
      BUILDKIT_PROGRESS: plain
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "src/yarn.lock" }}
      - run:
          name: Build
          command: ./build.sh
      - save_cache:
          key: node_modules-{{ checksum "src/yarn.lock" }}
          paths:
            - src/node_modules
  publish:
    machine:
      image: ubuntu-2404:current
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Publish
          command: docker images
#          command: ./publish.sh
      - run:
          name: Prune Docker Images
          command: docker image prune -f

workflows:
  build:
    jobs:
      - build-arm
      - build-x86
      - publish:
          requires:
            - build-arm
            - build-x86
